topics = [
    # 1–10
    "Agriculture & Farming",
    "Architecture & Design",
    "Artificial Intelligence & Machine Learning",
    "Arts & Culture",
    "Automotive & Transportation",
    "Aviation & Aerospace",
    "Blockchain & Cryptocurrency",
    "Business & Management",
    "Career & Professional Development",
    "Climate & Energy",

    # 11–20
    "Community & Local News",
    "Communication & Social Media",
    "Consumer Protection & Advocacy",
    "Cybersecurity & Information Security",
    "Data Science & Analytics",
    "Economics & Global Markets",
    "EdTech (Education Technology)",
    "Education & Academics",
    "E-commerce & Retail",
    "Entertainment & Media",

    # 21–30
    "Entrepreneurship & Startups",
    "Environment & Sustainability",
    "Family & Parenting",
    "Finance & Investing",
    "Food & Culinary",
    "Gaming & Esports",
    "Government & Politics",
    "Health & Wellness",
    "History & Heritage",
    "International Relations & Geopolitics",

    # 31–40
    "Journalism & Media Analysis",
    "Law & Legal Affairs",
    "Lifestyle & Fashion",
    "Marketing & Advertising",
    "Medicine & Healthcare",
    "Music & Performing Arts",
    "Outdoor & Adventure",
    "Personal Development & Self-Help",
    "Programming & Software Development",
    "Public Policy & Administration",

    # 41–50
    "Real Estate & Housing",
    "Religion & Spirituality",
    "Science & Research",
    "Space & Astronomy",
    "Security & Defense",
    "Society & Social Issues",
    "Sports & Athletics",
    "Technology & Innovation",
    "Travel & Tourism",
    "Writing & Publishing",
    "None"
]

subtopics = [
    "Market Analysis & Trends",
    "International Business & Trade",
    "Entrepreneurship & Startups",
    "Digital Transformation & Innovation",
    "Financial Markets & Investing",
    "Economic Policies & Reforms",
    "Public Health & Healthcare",
    "Disease Control & Research",
    "Mental Health & Wellbeing",
    "Local News & Community Issues",
    "Crime & Public Safety",
    "Government Policies & Public Administration",
    "International Relations & Diplomacy",
    "Geopolitics & Global Affairs",
    "Elections & Political Analysis",
    "Public Policy & Legislation",
    "Civil Rights & Social Justice",
    "Human Rights & Activism",
    "Education & Academia",
    "Higher Education & Student Life",
    "Science & Research Breakthroughs",
    "Climate Change & Environmental Issues",
    "Energy & Sustainability",
    "Agriculture & Farming Practices",
    "Technology & Hi-Tech Developments",
    "Artificial Intelligence & Machine Learning",
    "Programming & Software Development",
    "Cybersecurity & Data Protection",
    "Digital Marketing & E-commerce",
    "Social Media & Communication",
    "Consumer Electronics & Gadgets",
    "Open Source Software",
    "Cloud Computing & Virtualization",
    "Mobile Technology & Apps",
    "Data Science & Analytics",
    "Fintech & Cryptocurrency",
    "Blockchain & Decentralized Finance",
    "Automotive & Electric Vehicles",
    "Aviation & Aerospace",
    "Defense & Security Studies",
    "Humanities & Cultural Studies",
    "Art & Exhibitions",
    "Music & Performing Arts",
    "Film & Television",
    "Literature & Publishing",
    "Pop Culture & Entertainment",
    "Lifestyle & Fashion",
    "Food & Culinary Arts",
    "Travel & Tourism",
    "Hospitality & Leisure",
    "Sports & Athletics",
    "Team Sports & Leagues",
    "Adventure & Outdoor Activities",
    "Health & Wellness",
    "Nutrition & Diet",
    "Family & Parenting",
    "Relationships & Dating",
    "Psychology & Personal Development",
    "Philosophy & Ethics",
    "Religion & Spirituality",
    "Community Events & Local Governance",
    "Activism & Community Engagement",
    "Journalism & Investigative Reporting",
    "Media Analysis & Criticism",
    "Digital Rights & Privacy",
    "Startup Funding & Venture Capital",
    "Market Forecasts & Industry Insights",
    "Sustainability & Green Tech",
    "Energy Policy & Clean Technology",
    "Natural Disasters & Emergency Alerts",
    "Regional News & Cultural Identity",
    "Travel Guides & Destination Reviews",
    "Hospitality Industry & Hotels",
    "Transportation & Infrastructure",
    "Public Services & Safety",
    "Social Commentary & Opinion",
    "Public Health Initiatives & Awareness",
    "Baking & Culinary Tips",
    "Restaurant Reviews & Dining Trends",
    "Food Industry & Agriculture",
    "Global Conflicts & Peacekeeping",
    "International Law & Governance",
    "Community Health & Outreach",
    "Local Sports & Athletics",
    "Film Industry & Movie Reviews",
    "Television Shows & Reality TV",
    "Radio & Broadcasting",
    "Comedy & Humor",
    "Gaming & Esports",
    "Mobile Gaming & App Reviews",
    "Game Development & Design",
    "Music Festivals & Concerts",
    "Artist Interviews & Music Reviews",
    "Classical Music & Opera",
    "Cultural Events & Festivals",
    "Nature & Wildlife Conservation",
    "Marine Biology & Oceanography",
    "Racism & Discrimination",
    "History & Heritage Preservation",
    "Archaeology & Paleontology",
    "Biography & Memoir",
    "Book Reviews & Literary Analysis",
    "Podcasts & Interviews",
    "Entrepreneurship Culture & Community",
    "Tech Policy & Regulation",
    "UX Design & User Experience",
    "Entrepreneurship & Small Business",
    "Local Culture & Traditions",
    "Open Access & Academic Publishing",
    "Study Abroad & International Programs",
    "Child Development & Education",
    "Food Science & Nutrition",
    "Weather & Meteorology",
    "Agritech & Crop Management",
    "Music Industry Trends & Distribution",
    "International Entertainment & K-pop",
    "Documentaries & Indie Films",
    "Travel Rewards & Points Programs",
    "Local Gov & Administration",
    "Civic Engagement & Democracy",
    "Digital Humanities & Cultural Preservation",
    "Pharmaceuticals & Clinical Trials",
    "Biotechnology & Medical Research",
    "Mental Health & Counseling",
    "Sociology & Anthropology",
    "Global Economics & Market Trends",
    "Consumer Insights & Market Research",
    "Rural Development & Community Projects",
    "Urban Planning & Development",
    "Business Strategy & Leadership",
    "Open Source & Developer Communities",
    "SEO & Digital Marketing",
    "SaaS & Subscription Economy",
    "Defense Policy & Military Affairs",
    "Tax Policy & Financial Regulation",
    "Disaster Relief & Humanitarian Efforts",
    "Automotive Reviews & Comparisons",
    "Recipe Collections & Culinary Techniques",
    "Space Missions & Astronomy",
    "Pharmaceutical Policy & Healthcare Access",
    "Self-Care & Mindfulness",
    "Artisanal Crafts & DIY",
    "Child Welfare & Family Services",
    "Nonprofits & Philanthropy",
    "Public Transportation & Commute",
    "Spirituality & Religious Studies",
    "Financial Literacy & Budgeting",
    "Academic Writing & Research Skills",
    "Performing Arts & Theater",
    "Climate Action & Policy",
    "Surgical Innovations & Medical Devices",
    "Event Planning & Management",
    "Reality Show Recaps & Discussions",
    "Legislation & Political Debates",
    "Crime & Court Cases",
    "Fashion Industry & Trends",
    "Garden & Landscape Design",
    "Diversity & Inclusion",
    "Genealogy & Family History",
    "Cultural Heritage & Museums",
    "Ethnic Studies & Cultural Exploration",
    "Urban Culture & Street Art",
    "Photography & Visual Arts",
    "Podcasts & Audio Documentaries",
    "International Summits & Conferences",
    "Rural Affairs & Agriculture Policy",
    "Space Technology & Satellites",
    "Trade Agreements & Global Commerce",
    "Product Reviews & Unboxings",
    "Journalism Ethics & Media Freedoms",
    "Digital Tools & Productivity",
    "iOS & Android Development",
    "Tech Reviews & Comparisons",
    "Green Living & Eco-Friendly Practices",
    "Marine Conservation & Fisheries",
    "Disabled Rights & Accessibility",
    "Career Development & Vocational Training",
    "Philanthropy & Corporate Social Responsibility",
    "Elections & Voting Trends",
    "Footwear & Apparel",
    "Freelancing & Gig Economy",
    "Local Government & Public Affairs",
    "Nutritional Science & Dietetics",
    "Book Clubs & Reading Communities",
    "Podcast Production & Hosting",
    "Comedy & Stand-Up",
    "Outdoor Recreation & Hiking",
    "Web Hosting & Domain Management",
    "Land Use & Zoning",
    "Fitness & Bodybuilding",
    "Marriage & Relationship Counseling",
    "Child Welfare & Adoption",
    "Fashion Design & Merchandising",
    "Travel Photography & Videography",
    "Pharmacology & Drug Development",
    "Western Politics & Government",
    "Local Arts & Crafts Fairs",
    "Resort & Hospitality Management",
    "Productivity & Project Management",
    "Nutrition & Dietary Supplements",
    "Residential Real Estate",
    "Commercial Properties",
    "Mortgage & Financing",
    "Property Investment & Development",
    "Property Management & Leasing",
    "Smart Home & Real Estate Technology",
    "Online Learning Platforms",
    "Classroom Management Tools",
    "Interactive Content & Multimedia",
    "Assessment & Analytics Systems",
    "Adaptive Learning & AI",
    "Teacher Training & Professional Development",
    "Online Marketplaces",
    "Omnichannel Strategies",
    "Logistics & Fulfillment",
    "Customer Experience & Personalization",
    "Mobile Commerce & Apps",
    "B2B E-commerce Solutions",
    "None"
]

intended_audience = [
    "Business & Finance Professionals",
    "Tech Enthusiasts & Developers",
    "General Public",
    "Students & Academics",
    "News & Policy Followers",
    "Arts & Culture Enthusiasts",
    "Food & Culinary Lovers",
    "Sports & Fitness Fans",
    "Parents & Families",
    "Travel & Adventure Seekers",
    "Healthcare & Medical Professionals",
    "Environmental Advocates",
    "Music & Entertainment Fans",
    "Real Estate & Housing Stakeholders",
    "Gamers & eSports Fans",
    "Automotive & Motorcycle Enthusiasts",
    "Writers & Book Lovers",
    "Fashion & Beauty Followers",
    "Community & Local Residents",
    "Pet & Animal Lovers",
    "Law & Legal Professionals",
    "Spiritual & Religious Communities",
    "Marketing & Retail Professionals",
    "Personal Development & Self-Help Seekers",
    "Agriculture & Farming Communities",
    "Creative Professionals",  
    "Digital Nomads & Remote Workers",  
    "Holistic Health Enthusiasts",  
    "None"
]

tone = ['informative', 'neutral', 'critical', 'enthusiastic',
       'thought-provoking', 'urgent', 'supportive', "analytical", "None"]

content_type = ['factual', 'mixed', 'opinion-based', 'satirical', 'promotional', 'None']

update_frequency = ['multiple times daily', 'daily', 'weekly', 'monthly',"None"]
